name: Deploy site

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/566531503133/locations/global/workloadIdentityPools/github/providers/my-repo'
          service_account: 'gha-service-account@cs1660-assignment-5.iam.gserviceaccount.com?uid=103627196273721874279'

      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: 'site'
          destination: 'stb118-assignment-5'
          parent: false